version: "3.9"
services:
  app: 
    build: .
    stdin_open: true
    tty: true
    ports: 
      - 3000:3000
    working_dir: /app
    volumes: 
      - .:/app
    command: bash -c 'rails s -b 0.0.0.0'
    